### ISSUE TITLE
Source code is out-of-date

### ISSUE THREAD

**Issue by Mystyle-48** [RWS-Studios/POSTAL-SourceCode#1]
The source files of this repository are multiple changes behind the [last publicly available versions](https://web.archive.org/web/20190407150120mp_/https://bitbucket.org/gopostal/postal-1-open-source/downloads/) previously hosted on Bitbucket. 

- The game does not build in VS 2015 and newer due to using version 2.0.0 of the SDL2 static library, which was compiled before 2015’s changes to stdio. The Bitbucket repo uses version 2.0.5, which is compatible with VS 2015 and newer.
- The Steamworks build configuration is missing. 
- Multiple code changes present in the Bitbucket release are missing.

For example, here's [`input.cpp`](https://github.com/RWS-Studios/POSTAL-SourceCode/blob/main/input.cpp) on the left compared to the Bitbucket release on the right:

![image](https://github.com/RWS-Studios/POSTAL-SourceCode/assets/89315313/7390e82d-8d7c-4707-938c-3e4c7358bde3)

**Comment by Mystyle-48** [comment]
Building the debug executable confirms this; menu items from the [community-contributed November 2017 update](https://store.steampowered.com/news/app/232770/view/2909844527766289375), such as the level select, are missing from the main menu.

| Debug build (this repository) | Current build (Steam/GOG) |
|-------------| -------------|
|![image](https://github.com/RWS-Studios/POSTAL-SourceCode/assets/89315313/21e1bc87-8b62-4697-85a5-e6a26690a3d7)|![image](https://github.com/RWS-Studios/POSTAL-SourceCode/assets/89315313/e3457319-7c8a-4776-9481-d8c09e408711)

**Comment by Wingzzzzy** [comment]
I am not sure if its the real RWS account. I will contact someone that i know from the company.

**Comment by Mystyle-48** [comment]
> I am not sure if its the real RWS account. I will contact someone that i know from the company.

It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.

**Comment by Wingzzzzy** [comment]
> > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> 
> It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.

Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.

**Comment by Mystyle-48** [comment]
> > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > 
> > 
> > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> 
> Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.

I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.

**Comment by Wingzzzzy** [comment]
> > > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > > 
> > > 
> > > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> > 
> > 
> > Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.
> 
> I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.

Who did you email as mike is gone on vacation.

**Comment by Mystyle-48** [comment]
> > > > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > > > 
> > > > 
> > > > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> > > 
> > > 
> > > Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.
> > 
> > 
> > I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.
> 
> Who did you email as mike is gone on vacation.

pedro@gopostal.com?

**Comment by Wingzzzzy** [comment]
> > > > > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > > > > 
> > > > > 
> > > > > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> > > > 
> > > > 
> > > > Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.
> > > 
> > > 
> > > I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.
> > 
> > 
> > Who did you email as mike is gone on vacation.
> 
> [pedro@gopostal.com](mailto:pedro@gopostal.com)?

I am telling him to check his email. As i an just in a call with him on discord trying to understand how to build this.

**Comment by Mystyle-48** [comment]
> > > > > > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > > > > > 
> > > > > > 
> > > > > > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> > > > > 
> > > > > 
> > > > > Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.
> > > > 
> > > > 
> > > > I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.
> > > 
> > > 
> > > Who did you email as mike is gone on vacation.
> > 
> > 
> > [pedro@gopostal.com](mailto:pedro@gopostal.com)?
> 
> I am telling him to check his email. As i an just in a call with him on discord trying to understand how to build this.

If you're using Visual Studio 2015 or newer, you cannot build the codebase from this repo in its current state due to the aforementioned issues. For now you'll want to use the [Bitbucket version](https://web.archive.org/web/20190425201917/https://bitbucket.org/gopostal/postal-1-open-source) instead. 

I made a [pull request](https://github.com/RWS-Studios/POSTAL-SourceCode/pull/2) that properly updates this repo to the one last found on Bitbucket before it went down. I'm waiting for it to be accepted.

**Comment by Wingzzzzy** [comment]
> > > > > > > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > > > > > > 
> > > > > > > 
> > > > > > > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> > > > > > 
> > > > > > 
> > > > > > Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.
> > > > > 
> > > > > 
> > > > > I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.
> > > > 
> > > > 
> > > > Who did you email as mike is gone on vacation.
> > > 
> > > 
> > > [pedro@gopostal.com](mailto:pedro@gopostal.com)?
> > 
> > 
> > I am telling him to check his email. As i an just in a call with him on discord trying to understand how to build this.
> 
> If you're using Visual Studio 2015 or newer, you cannot build the codebase from this repo in its current state due to the aforementioned issues. For now you'll want to use the [Bitbucket version](https://web.archive.org/web/20190425201917/https://bitbucket.org/gopostal/postal-1-open-source) instead.
> 
> I made a [pull request](https://github.com/RWS-Studios/POSTAL-SourceCode/pull/2) that properly updates this repo to the one last found on Bitbucket before it went down. I'm waiting for it to be accepted.

Let's see if Mike J controls this account, will take a while. Pedro might try to get in or get someone who knows how to use GitHub to accept the pull request.

**Comment by Mystyle-48** [comment]
> > > > > > > > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> > > > > > > 
> > > > > > > 
> > > > > > > Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.
> > > > > > 
> > > > > > 
> > > > > > I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.
> > > > > 
> > > > > 
> > > > > Who did you email as mike is gone on vacation.
> > > > 
> > > > 
> > > > [pedro@gopostal.com](mailto:pedro@gopostal.com)?
> > > 
> > > 
> > > I am telling him to check his email. As i an just in a call with him on discord trying to understand how to build this.
> > 
> > 
> > If you're using Visual Studio 2015 or newer, you cannot build the codebase from this repo in its current state due to the aforementioned issues. For now you'll want to use the [Bitbucket version](https://web.archive.org/web/20190425201917/https://bitbucket.org/gopostal/postal-1-open-source) instead.
> > I made a [pull request](https://github.com/RWS-Studios/POSTAL-SourceCode/pull/2) that properly updates this repo to the one last found on Bitbucket before it went down. I'm waiting for it to be accepted.
> 
> Let's see if Mike J controls this account, will take a while. Pedro might try to get in or get someone who knows how to use GitHub to accept the pull request.

Alright. I appreciate you for going the extra mile to make direct contact with the team. Let's see how it goes.

**Comment by Wingzzzzy** [comment]
> > > > > > > > > > I am not sure if its the real RWS account. I will contact someone that i know from the company.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It is. The [source code release blog post on RunningWithScissors.com](https://runningwithscissors.com/the-original-postal-has-been-made-open-source/) has been updated to link directly to this repository.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Intresting. as i am working on a project with them and one of the people working in there also did not know if it was their account.
> > > > > > > 
> > > > > > > 
> > > > > > > I emailed RWS about the source code issue last night, so I'm just now waiting for a response. Presumably from someone within who is aware of this GitHub repo.
> > > > > > 
> > > > > > 
> > > > > > Who did you email as mike is gone on vacation.
> > > > > 
> > > > > 
> > > > > [pedro@gopostal.com](mailto:pedro@gopostal.com)?
> > > > 
> > > > 
> > > > I am telling him to check his email. As i an just in a call with him on discord trying to understand how to build this.
> > > 
> > > 
> > > If you're using Visual Studio 2015 or newer, you cannot build the codebase from this repo in its current state due to the aforementioned issues. For now you'll want to use the [Bitbucket version](https://web.archive.org/web/20190425201917/https://bitbucket.org/gopostal/postal-1-open-source) instead.
> > > I made a [pull request](https://github.com/RWS-Studios/POSTAL-SourceCode/pull/2) that properly updates this repo to the one last found on Bitbucket before it went down. I'm waiting for it to be accepted.
> > 
> > 
> > Let's see if Mike J controls this account, will take a while. Pedro might try to get in or get someone who knows how to use GitHub to accept the pull request.
> 
> Alright. I appreciate you for going the extra mile to make direct contact with the team. Let's see how it goes.

No wories, fun fact they forgot they even had a official github account when they asked me to help them with organising a Web Version of postal.

**Comment by Wingzzzzy** [comment]
@Mystyle-48 Where would be the best place to contact you for any more questions about the source code?

**Comment by Mystyle-48** [comment]
@Wingzzzzy I am in the RWS Discord server, I'll send a message.

**Comment by RWS-Studios** [comment]
Really sorry for the delay on this guys. Fixed!

**Comment by Mystyle-48** [comment]
@RWS-Studios Awesome! Thank you!
